name: Build and Deploy on Merge

on:
  push:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev-draghav, qa-draghav, prod-draghav]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Tag Image
        run: |
          docker build -t my-app-${{ matrix.env }}:${{ github.sha }} ./${{ matrix.env }}

      - name: Notify Teams
        if: always()
        run: |
          status="${{ job.status }}"
          payload="{
            \"@type\": \"MessageCard\",
            \"@context\": \"https://schema.org/extensions\",
            \"summary\": \"GitHub Actions Notification\",
            \"themeColor\": \"0076D7\",
            \"title\": \"Build - $status\",
            \"text\": \"Repository: **${{ github.repository }}**<br>Branch: **${{ github.ref_name }}**<br>Workflow: **${{ github.workflow }}**<br>Status: **$status**<br>Commit: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\"
          }"
          curl -H "Content-Type: application/json" -d "$payload" ${{ secrets.TEAMS_WEBHOOK_URL }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        env: [dev-draghav, qa-draghav, prod-draghav]

    environment:
      name: ${{ matrix.env }}
      url: https://my-app-${{ matrix.env }}.example.com 

    steps:
      - name: Deploy to ${{ matrix.env }}
        run: echo "Deploying image to ${{ matrix.env }}"

      - name: Notify Teams
        if: always()
        run: |
          status="${{ job.status }}"
          payload="{
            \"@type\": \"MessageCard\",
            \"@context\": \"https://schema.org/extensions\",
            \"summary\": \"GitHub Actions Notification\",
            \"themeColor\": \"0076D7\",
            \"title\": \"Deploy - $status\",
            \"text\": \"Repository: **${{ github.repository }}**<br>Branch: **${{ github.ref_name }}**<br>Workflow: **${{ github.workflow }}**<br>Status: **$status**<br>Commit: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\"
          }"
          curl -H "Content-Type: application/json" -d "$payload" ${{ secrets.TEAMS_WEBHOOK_URL }}