name: PR Build Workflow

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev-draghav, qa-draghav, prod-draghav]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ matrix.env }}:${{ github.sha }} ./${{ matrix.env }}
